### ISSUE TITLE
Config.go file missing NetworkId for testnet

### ISSUE THREAD

**Issue by cemdenizsel** [aurora-is-near/near-api-go#15]
Hi Aurora Team,

In the config.go file, inside GetConfig() file testnet case is handled as default case and the networkId of testnet becomes `default`. But it should be `testnet`. In order to find credentials under home/.near-credentials it looks for `default` but actually there is a folder called `testnet` so it cannot find it. Appreciate it if you add a networkId option under testnet such as `testnet`. So it can find the correct folder. 
![image](https://github.com/aurora-is-near/near-api-go/assets/45531291/40e739bb-2a33-40e1-b1ba-2323dfe9a6fe)

Thank you.

**Comment by spilin** [comment]
Thank you for reporting this @cemdenizsel . Fixed and merged.
